### ISSUE TITLE
opp_charttool in omnetpp-6.0.1 does not work

### ISSUE THREAD

**Issue by avarga** [omnetpp/opp_env#12]
```
Traceback (most recent call last):
  File "/home/andras/projects/opp_env_workspaces/tmp/omnetpp-6.0.1/bin/opp_charttool", line 170, in <module>
    analysis.run_chart(chart, anf_dir, workspace, show=args.show, extra_props=props)
  File "/home/andras/projects/opp_env_workspaces/tmp/omnetpp-6.0.1/python/omnetpp/scave/analysis.py", line 412, in run_chart
    plt.clf()
  File "/nix/store/3kx8idqvwa181cj92hlcvh6jizaa6pjg-python3.10-matplotlib-3.7.0/lib/python3.10/site-packages/matplotlib/pyplot.py", line 970, in clf
    gcf().clear()
  File "/nix/store/3kx8idqvwa181cj92hlcvh6jizaa6pjg-python3.10-matplotlib-3.7.0/lib/python3.10/site-packages/matplotlib/pyplot.py", line 879, in gcf
    return figure()
  File "/nix/store/3kx8idqvwa181cj92hlcvh6jizaa6pjg-python3.10-matplotlib-3.7.0/lib/python3.10/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "/nix/store/3kx8idqvwa181cj92hlcvh6jizaa6pjg-python3.10-matplotlib-3.7.0/lib/python3.10/site-packages/matplotlib/pyplot.py", line 813, in figure
    manager = new_figure_manager(
  File "/nix/store/3kx8idqvwa181cj92hlcvh6jizaa6pjg-python3.10-matplotlib-3.7.0/lib/python3.10/site-packages/matplotlib/pyplot.py", line 383, in new_figure_manager
    return _get_backend_mod().new_figure_manager(*args, **kwargs)
  File "/nix/store/3kx8idqvwa181cj92hlcvh6jizaa6pjg-python3.10-matplotlib-3.7.0/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 3570, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/nix/store/3kx8idqvwa181cj92hlcvh6jizaa6pjg-python3.10-matplotlib-3.7.0/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 3575, in new_figure_manager_given_figure
    return cls.FigureCanvas.new_manager(figure, num)
  File "/nix/store/3kx8idqvwa181cj92hlcvh6jizaa6pjg-python3.10-matplotlib-3.7.0/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 1738, in new_manager
    return cls.manager_class.create_with_canvas(cls, figure, num)
  File "/nix/store/3kx8idqvwa181cj92hlcvh6jizaa6pjg-python3.10-matplotlib-3.7.0/lib/python3.10/site-packages/matplotlib/backends/_backend_tk.py", line 483, in create_with_canvas
    window = tk.Tk(className="matplotlib")
  File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable tk.tcl in the following directories: 
    /nix/store/ax09cbfj991hn856w1pmk68mxbf6lcfl-tcl-8.6.13/lib/tcl8.6/tk8.6 /nix/store/ax09cbfj991hn856w1pmk68mxbf6lcfl-tcl-8.6.13/lib/tk8.6 /nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/tk8.6 /nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/tk8.6 /nix/store/lib/tk8.6 /nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/library

This probably means that tk wasn't installed properly.

```

Maybe Qt  backend should be specified to Matplotlib somehow, if Tcl/Tk is not present? (or maybe Qt should be the default, and only use Tcl/Tk if Qt does not work?)

**Comment by avarga** [comment]
Maybe this is an opp_charttool issue not opp_env.

**Comment by avarga** [comment]
Using the Qt back doesn't work either, due to lack of necessary libs.

```
$ MPLBACKEND=qtagg opp_charttool run SatShowcase.anf -p inet=../../../.. 
[...]
ImportError: Failed to import any of the following Qt binding modules: PyQt6, PySide6, PyQt5, PySide2
```

**Comment by avarga** [comment]
Fixed by adding the "python3Packages.pyqt5" nix package to omnetpp-6+
