### ISSUE TITLE
Nix package is not working

### ISSUE THREAD

**Issue by SeineEloquenz** [omnetpp/opp_env#16]
I'm trying to build the `opp_env` nix package to use Omnet++ on NixOS, but the build errors out and complains about a missing version for `setuptools-scm`. When I uncomment `SETUPTOOLS_SCM_PRETEND_VERSION` the build continues, but ultimately errors because of a missing pip dependency.

Am I doing something wrong or is there some other way to get Omnet++ running on NixOS? Because the packages [here](https://github.com/omnetpp/omnetpp-nix) are outdated and currently I'm forced to dualboot into Arch to use Omnet++.

<details>
<summary>Build with clean repo</summary>

```
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/a5rh0j3maqq05d5j1fi31h81k7z3idpk-xzm32ac4w923rcv9kr6rfsyvn5ak0cn1-source
source root is xzm32ac4w923rcv9kr6rfsyvn5ak0cn1-source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file xzm32ac4w923rcv9kr6rfsyvn5ak0cn1-source/tests/test_oppenv
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "/build/xzm32ac4w923rcv9kr6rfsyvn5ak0cn1-source/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 5, in <module>
    setup()
  File "/nix/store/49pg4ljx6qandwdr6mbc8w8k8fh0dd2j-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/49pg4ljx6qandwdr6mbc8w8k8fh0dd2j-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
  File "/nix/store/49pg4ljx6qandwdr6mbc8w8k8fh0dd2j-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/dist.py", line 476, in __init__
    _Distribution.__init__(
  File "/nix/store/49pg4ljx6qandwdr6mbc8w8k8fh0dd2j-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 280, in __init__
    self.finalize_options()
  File "/nix/store/49pg4ljx6qandwdr6mbc8w8k8fh0dd2j-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/dist.py", line 900, in finalize_options
    ep(self)
  File "/nix/store/hsa5i9m2yihaiq3cags38cldvj9paisq-python3.10-setuptools-scm-7.0.5/lib/python3.10/site-packages/setuptools_scm/integration.py", line 123, in infer_version
    _assign_version(dist, config)
  File "/nix/store/hsa5i9m2yihaiq3cags38cldvj9paisq-python3.10-setuptools-scm-7.0.5/lib/python3.10/site-packages/setuptools_scm/integration.py", line 62, in _assign_version
    _version_missing(config)
  File "/nix/store/hsa5i9m2yihaiq3cags38cldvj9paisq-python3.10-setuptools-scm-7.0.5/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 109, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for /build/xzm32ac4w923rcv9kr6rfsyvn5ak0cn1-source.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```
</details>

<details>
<summary>Build with PRETENDVERSION</summary>

```
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/f8cabszw38q7pyj3kk4vzpnn0kdmb4al-4ajmdzm5ascj959i5x198yx6bdc7y810-source
source root is 4ajmdzm5ascj959i5x198yx6bdc7y810-source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file 4ajmdzm5ascj959i5x198yx6bdc7y810-source/tests/test_oppenv
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Executing setuptoolsBuildPhase
failed to parse version dirty.20231109
Traceback (most recent call last):
  File "/nix/store/hsa5i9m2yihaiq3cags38cldvj9paisq-python3.10-setuptools-scm-7.0.5/lib/python3.10/site-packages/setuptools_scm/_version_cls.py", line 36, in _version_as_tuple
    parsed_version = Version(version_str)
  File "/nix/store/myyr3gvkqc7qdcwz5rgp63as3gchcsw5-python3.10-packaging-21.3/lib/python3.10/site-packages/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'dirty.20231109'
/nix/store/49pg4ljx6qandwdr6mbc8w8k8fh0dd2j-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/dist.py:544: UserWarning: The version specified ('dirty.20231109') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
/nix/store/49pg4ljx6qandwdr6mbc8w8k8fh0dd2j-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/opp_env
copying opp_env/external_versions.py -> build/lib/opp_env
copying opp_env/simulte_versions.py -> build/lib/opp_env
copying opp_env/opp_env.py -> build/lib/opp_env
copying opp_env/omnetpp_versions.py -> build/lib/opp_env
copying opp_env/__main__.py -> build/lib/opp_env
copying opp_env/simu5g_versions.py -> build/lib/opp_env
copying opp_env/veins_versions.py -> build/lib/opp_env
copying opp_env/inet_versions.py -> build/lib/opp_env
copying opp_env/__init__.py -> build/lib/opp_env
copying opp_env/_version.py -> build/lib/opp_env
running egg_info
/nix/store/49pg4ljx6qandwdr6mbc8w8k8fh0dd2j-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: dirty.20231109 is an invalid version and will not be supported in a future release
  warnings.warn(
creating opp_env.egg-info
writing opp_env.egg-info/PKG-INFO
writing dependency_links to opp_env.egg-info/dependency_links.txt
writing entry points to opp_env.egg-info/entry_points.txt
writing requirements to opp_env.egg-info/requires.txt
writing top-level names to opp_env.egg-info/top_level.txt
writing manifest file 'opp_env.egg-info/SOURCES.txt'
reading manifest file 'opp_env.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'opp_env.egg-info/SOURCES.txt'
/nix/store/49pg4ljx6qandwdr6mbc8w8k8fh0dd2j-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/opp_env
copying build/lib/opp_env/external_versions.py -> build/bdist.linux-x86_64/wheel/opp_env
copying build/lib/opp_env/simulte_versions.py -> build/bdist.linux-x86_64/wheel/opp_env
copying build/lib/opp_env/opp_env.py -> build/bdist.linux-x86_64/wheel/opp_env
copying build/lib/opp_env/omnetpp_versions.py -> build/bdist.linux-x86_64/wheel/opp_env
copying build/lib/opp_env/__main__.py -> build/bdist.linux-x86_64/wheel/opp_env
copying build/lib/opp_env/simu5g_versions.py -> build/bdist.linux-x86_64/wheel/opp_env
copying build/lib/opp_env/veins_versions.py -> build/bdist.linux-x86_64/wheel/opp_env
copying build/lib/opp_env/inet_versions.py -> build/bdist.linux-x86_64/wheel/opp_env
copying build/lib/opp_env/__init__.py -> build/bdist.linux-x86_64/wheel/opp_env
copying build/lib/opp_env/_version.py -> build/bdist.linux-x86_64/wheel/opp_env
running install_egg_info
Copying opp_env.egg-info to build/bdist.linux-x86_64/wheel/opp_env-dirty.20231109-py3.10.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
creating build/bdist.linux-x86_64/wheel/opp_env-dirty.20231109.dist-info/WHEEL
creating 'dist/opp_env-dirty.20231109-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'opp_env/__init__.py'
adding 'opp_env/__main__.py'
adding 'opp_env/_version.py'
adding 'opp_env/external_versions.py'
adding 'opp_env/inet_versions.py'
adding 'opp_env/omnetpp_versions.py'
adding 'opp_env/opp_env.py'
adding 'opp_env/simu5g_versions.py'
adding 'opp_env/simulte_versions.py'
adding 'opp_env/veins_versions.py'
adding 'opp_env-dirty.20231109.dist-info/LICENSE'
adding 'opp_env-dirty.20231109.dist-info/METADATA'
adding 'opp_env-dirty.20231109.dist-info/WHEEL'
adding 'opp_env-dirty.20231109.dist-info/entry_points.txt'
adding 'opp_env-dirty.20231109.dist-info/top_level.txt'
adding 'opp_env-dirty.20231109.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Finished executing setuptoolsBuildPhase
@nix { "action": "setPhase", "phase": "installPhase" }
installing
Executing pipInstallPhase
/build/4ajmdzm5ascj959i5x198yx6bdc7y810-source/dist /build/4ajmdzm5ascj959i5x198yx6bdc7y810-source
Processing ./opp_env-dirty.20231109-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement pip>=23.0.0 (from opp-env) (from versions: none)
ERROR: No matching distribution found for pip>=23.0.0
```
</details>

**Comment by rhornig** [comment]
I'm confused here. I'm not aware of any `opp_env` nix packages. `opp_env` is a python module that should be installed with `pip3 install --user --break-system-packages git+https://github.com/omnetpp/opp_env.git` once python3, pip, curl and git is installed by your OS package manager (which is NIX in your case).

I've just installed `opp_env` on nixOS with the above command. Are you trying to actually build a proper nix package from the `opp_env` repo?

At the moment `opp_env` is intended to be installed into a python virtual environment set up  (and activated) somewhere in your home directory (or in the global system environment if you use the --bareak-system-packages switch during the installation).

(on longer term I'm indeed planning to create a proper opp_env nix package and possibly submit it to `nixpackages`. At the moment, you can install only from the git repo with the above command. Neither PyPi or NIX package exist.

**Comment by SeineEloquenz** [comment]
Yes, the flake in this repository exposes an `opp_env` package that I tried to build because I assumed this were a possible way for installation. I'll try the pip way instead for now. Thanks for clarifying!
