### ISSUE TITLE
Failed to install omnetpp

### ISSUE THREAD

**Issue by gatsby0203** [omnetpp/opp_env#17]
**Environment**

| Name   | Version |
| ------ | ------- |
| OS     | RHEL 8.9     |
| NIX    | 2.19.2  |
| Python | 3.9.18  |
| tar    | 1.30    |
| gzip   | 1.9     |

> PS. running nix under `nix-user-chroot` with a conda environment.

**Debug Output**

```shell
opp_env -d install omnetpp-6.0.2
DEBUG Starting install operation
DEBUG Running nix --version
DEBUG Workspace root_directory='/home/gatsby/Software/omnetpp', self.nixless=False
DEBUG Computing list of effective projects for [omnetpp-6.0.2]
DEBUG Selecting options None for project omnetpp-6.0.2
INFO Using specified projects [omnetpp-6.0.2] with effective projects [omnetpp-6.0.2] in workspace /home/gatsby/Software/omnetpp
INFO Downloading project omnetpp-6.0.2 in workspace /home/gatsby/Software/omnetpp
https://github.com/omnetpp/omnetpp/releases/download/omnetpp-6.0.2/omnetpp-6.0.2-linux-x86_64.tgz
DEBUG Using nixpkgs 22.11 with llvmPackages.stdenv, packages: bashInteractive coreutils curl findutils git gnused gnutar gzip openssh perl which
DEBUG Nix flake shellHook script:
    cd /home/gatsby/Software/omnetpp/omnetpp-6.0.2 && curl -L --fail --progress-bar https://github.com/omnetpp/omnetpp/releases/download/omnetpp-6.0.2/omnetpp-6.0.2-linux-x86_64.tgz | tar --strip-components=1 -xzf - 2>/home/gatsby/Software/omnetpp/omnetpp-6.0.2/tar.log
DEBUG Running command: nix --extra-experimental-features nix-command --extra-experimental-features flakes develop -i -k HOME -k TERM -k COLORTERM -k DISPLAY -k XAUTHORITY -k XDG_RUNTIME_DIR -k XDG_DATA_DIRS -k XDG_CACHE_HOME -k QT_AUTO_SCREEN_SCALE_FACTOR /home/gatsby/Software/omnetpp/.opp_env_workspace/22.11 -c true
curl: (35) error:16000069:STORE routines::unregistered scheme                                                                                                                       

DEBUG Exit code: 2
gzip: warning: GZIP environment variable is deprecated; use an alias or script

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
INFO Error during download, cleaning up
Traceback (most recent call last):
  File "/home/gatsby/.local/bin/opp_env", line 8, in <module>
    sys.exit(main())
  File "/home/gatsby/.local/lib/python3.9/site-packages/opp_env/opp_env.py", line 1719, in main
    raise e
  File "/home/gatsby/.local/lib/python3.9/site-packages/opp_env/opp_env.py", line 1701, in main
    install_subcommand_main(**kwargs)
  File "/home/gatsby/.local/lib/python3.9/site-packages/opp_env/opp_env.py", line 1520, in install_subcommand_main
    workspace.download_project_if_needed(project_description, effective_project_descriptions, **kwargs)
  File "/home/gatsby/.local/lib/python3.9/site-packages/opp_env/opp_env.py", line 1008, in download_project_if_needed
    self.download_project(project_description, effective_project_descriptions, patch, cleanup, **kwargs)
  File "/home/gatsby/.local/lib/python3.9/site-packages/opp_env/opp_env.py", line 933, in download_project
    raise e
  File "/home/gatsby/.local/lib/python3.9/site-packages/opp_env/opp_env.py", line 889, in download_project
    self.download_and_unpack_tarball(project_description.download_url, project_dir)
  File "/home/gatsby/.local/lib/python3.9/site-packages/opp_env/opp_env.py", line 1038, in download_and_unpack_tarball
    raise e
  File "/home/gatsby/.local/lib/python3.9/site-packages/opp_env/opp_env.py", line 1034, in download_and_unpack_tarball
    self.run_command(f"cd {target_folder} && curl -L --fail --progress-bar {download_url} | tar --strip-components=1 -xzf - 2>{tar_log_file}")
  File "/home/gatsby/.local/lib/python3.9/site-packages/opp_env/opp_env.py", line 1313, in run_command
    return self._do_nix_develop(nixos=self.default_nixos, stdenv=self.default_stdenv, session_name="run_command", script=command,
  File "/home/gatsby/.local/lib/python3.9/site-packages/opp_env/opp_env.py", line 1304, in _do_nix_develop
    result = self._do_run_command(nix_develop_command, env=env, suppress_stdout=not interactive and suppress_stdout, check_exitcode=check_exitcode)
  File "/home/gatsby/.local/lib/python3.9/site-packages/opp_env/opp_env.py", line 1334, in _do_run_command
    raise Exception(f"Child process exit code {result.returncode}")
Exception: Child process exit code 2
```

**Comment by rhornig** [comment]
It looks like Github did not return the correct archive file to be extracted. 

In an empty directory try to execute `curl -L --fail --progress-bar https://github.com/omnetpp/omnetpp/releases/download/omnetpp-6.0.2/omnetpp-6.0.2-linux-x86_64.tgz | tar --strip-components=1 -xzf -`

It should extract the omnetpp installation there. It looks like there was a network/server problem and github did not return the proper archive. (I've just tried the above command and it works for me).

**Comment by gatsby0203** [comment]
> It looks like Github did not return the correct archive file to be extracted.
> 
> In an empty directory try to execute `curl -L --fail --progress-bar https://github.com/omnetpp/omnetpp/releases/download/omnetpp-6.0.2/omnetpp-6.0.2-linux-x86_64.tgz | tar --strip-components=1 -xzf -`
> 
> It should extract the omnetpp installation there. It looks like there was a network/server problem and github did not return the proper archive. (I've just tried the above command and it works for me).

It turned out an internet connection issue. 
I've executed `curl -L --fail --progress-bar https://github.com/omnetpp/omnetpp/releases/download/omnetpp-6.0.2/omnetpp-6.0.2-linux-x86_64.tgz | tar --strip-components=1 -xzf -` and it worked, however, the issue remains when I try `opp_env install omnetpp-latest`. Things get tricky when you are in China.
but no worries, I've figured it out. I updated some proxy settings and it worked.

Thank you for your reply.

**Comment by rhornig** [comment]
Hmm, at least a bit better error message would be useful. Closing this now.
